### ISSUE TITLE
Could You Open a PR to DefinitelyTyped

### ISSUE THREAD

**Issue by bliles** [calebsander/vue-material-types#1]
Thanks for providing these types, but have you considered opening a PR to https://github.com/DefinitelyTyped/DefinitelyTyped? If it gets incorporated there the types will be available in a location that developers can easily install it (npm install @types/vue-material)

**Comment by calebsander** [comment]
I believe Vue Material is going to release version 1.0.0 soon and these type declarations (which are for 0.x.x versions) will become obsolete. It would be great if someone wanted to make type declarations for the new API and add them to DefinitelyTyped, but I only made these for projects of mine that were running 0.x.x.
